USE flask_todo_app;
CREATE TABLE users(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(25), username VARCHAR(25), email VARCHAR(50), password VARCHAR(100), register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tasks(id INT PRIMARY KEY AUTO_INCREMENT, author VARCHAR(25), description TEXT , status VARCHAR(25), create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
